[package]
name = "digits-nn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
nalgebra = "0.30.1"
rand = "0.8.5"
ron = "0.7.0"
serde = "1.0.136"
